# This file was generated by GoReleaser. DO NOT EDIT.
cask "cert" do
  name "cert"
  desc "Certificate and TLS swiss army knife."
  homepage "https://github.com/kisom/cert"
  version "1.4.2"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on formula: [
      "curl",
    ]

  on_macos do
    on_intel do
      url "https://github.com/kisom/cert/releases/download/v#{version}/cert_darwin_amd64_v#{version}",
        using: :homebrew_curl
      sha256 "948e7eb5a0471fba3942dd32c19c40956efc4c649c217d75119c7eb100cdd36c"
      binary "cert_darwin_amd64_v1.4.2", target: "cert"
    end
    on_arm do
      url "https://github.com/kisom/cert/releases/download/v#{version}/cert_darwin_arm64_v#{version}",
        using: :homebrew_curl
      sha256 "5c2902fe1811188466ecbe3553bedf01871d6910acc00486c352aa37fbb88390"
      binary "cert_darwin_arm64_v1.4.2", target: "cert"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kisom/cert/releases/download/v#{version}/cert_linux_amd64_v#{version}",
        using: :homebrew_curl
      sha256 "d38ea2719ec0a892b0a29f7e33c2b49af73a0b49ca8967dbfb0b3357817654f9"
      binary "cert_linux_amd64_v1.4.2", target: "cert"
    end
    on_arm do
      url "https://github.com/kisom/cert/releases/download/v#{version}/cert_linux_arm64_v#{version}",
        using: :homebrew_curl
      sha256 "4f2d3aef60e9c8def4f2fa76609eaf2db4947011a1abe058ebe2bb26df85da43"
      binary "cert_linux_arm64_v1.4.2", target: "cert"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cert"]
    end
  end

  # No zap stanza required
end
