# This file was generated by GoReleaser. DO NOT EDIT.
cask "cert" do
  name "cert"
  desc "Certificate and TLS swiss army knife."
  homepage "https://github.com/kisom/cert"
  version "1.3.11"

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_intel do
      url "https://github.com/kisom/cert/releases/download/v#{version}/cert_Darwin_x86_64 _#{version}",
        using: :homebrew_curl
      sha256 "1daa6c6bf6aed4e6a98fa7a0db09da51af4e11281a584471dab2f4ff14be40bd"
      binary "cert_Darwin_x86_64 _1.3.11", target: "cert"
    end
    on_arm do
      url "https://github.com/kisom/cert/releases/download/v#{version}/cert_Darwin_arm64 _#{version}",
        using: :homebrew_curl
      sha256 "1c7a5d104e1b47f8a042be3b2724efc18b559207cf8d98670e4f9185318ca99e"
      binary "cert_Darwin_arm64 _1.3.11", target: "cert"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kisom/cert/releases/download/v#{version}/cert_Linux_x86_64 _#{version}",
        using: :homebrew_curl
      sha256 "5461547064ba5922449b36bba1c2a8615a37ef8b4265d8b3c7c372af2732be6d"
      binary "cert_Linux_x86_64 _1.3.11", target: "cert"
    end
    on_arm do
      url "https://github.com/kisom/cert/releases/download/v#{version}/cert_Linux_arm64 _#{version}",
        using: :homebrew_curl
      sha256 "1186ca6b9ebbb0a8d179522fb054fc8775d962762ad7e5a1554256347ed3c245"
      binary "cert_Linux_arm64 _1.3.11", target: "cert"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cert"]
    end
  end

  # No zap stanza required
end
