# This file was generated by GoReleaser. DO NOT EDIT.
cask "cert" do
  name "cert"
  desc "Certificate and TLS swiss army knife."
  homepage "https://github.com/kisom/cert"
  version "1.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on formula: [
      "curl",
    ]

  on_macos do
    on_intel do
      url "https://github.com/kisom/cert/releases/download/v#{version}/cert_darwin_amd64_v#{version}",
        using: :homebrew_curl
      sha256 "deb3e4e78674b33a325d705a3527aff40935ff6227f6268253657a7d19a671ff"
      binary "cert_darwin_amd64_v1.4.0", target: "cert"
    end
    on_arm do
      url "https://github.com/kisom/cert/releases/download/v#{version}/cert_darwin_arm64_v#{version}",
        using: :homebrew_curl
      sha256 "843bbbc35061ef5e73ebf217b6e61cd3782df4916815c9e541d1427c8a190a7c"
      binary "cert_darwin_arm64_v1.4.0", target: "cert"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kisom/cert/releases/download/v#{version}/cert_linux_amd64_v#{version}",
        using: :homebrew_curl
      sha256 "69496769a513d3f457a44fc73b2689b0b6b49b6a4aa4f426ff124d0f3d8d8ec5"
      binary "cert_linux_amd64_v1.4.0", target: "cert"
    end
    on_arm do
      url "https://github.com/kisom/cert/releases/download/v#{version}/cert_linux_arm64_v#{version}",
        using: :homebrew_curl
      sha256 "483e071706f9437d91c870f6357710af781691c6831a90fd9627b91cdd8fe6c1"
      binary "cert_linux_arm64_v1.4.0", target: "cert"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cert"]
    end
  end

  # No zap stanza required
end
